name: Python CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --no-root
          poetry shell
      - name: Lint
        run: flake8 --show-source .
      - name: Type Check
        run: mypy
      - name: Test
        run: python -m unittest discover -v
