name: Python CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v1
      - name: Install dependencies
        run: poetry install --no-root
      - name: Lint
        run: |
          poetry run flake8 --show-source .
          poetry run poetry run black . --check
          poetry run isort -rc -sl -c .
      - name: Type Check
        run: poetry run mypy
      - name: Test
        run: poetry run pytest
